[tool.poetry]
name = "PCParadisebot"
version = "1.0.0"
description = "A small discord bot for pcparadise"
# all the people who've developed on this project can be found
# on the github repo, only the original author is written below.
authors = ["Arvinder Dhanoa <awsomearvinder@gmail.com>"]
maintainers = [ "Ganoosh <swajabbadaja@gmail.com>" ]
license = "MIT"
packages = [
  { include = "src" }
]

[tool.poetry.dependencies]
'discord.py' = "^1.7"
appdirs = "^1.4"
python = "^3.9"
fuzzywuzzy = "^0.18"

[tool.poetry.dev-dependencies]
black = "20.8b1"
pylint = "2.7.4"

[tool.poetry.scripts]
run = "src.main:main"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.core.masonry.api"
