name: lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: install pylint
        run: pip install pylint
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: check pylint
        run: pylint **/*.py
