name: lint
on: [pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Setup python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.9
            - name: install pylint
              run: pip install pylint
            - name: check pylint
              run: pylint **/*.py
